# Zeabur配置文件
version: "1"

# 服务配置
services:
  - type: web
    name: btc-4hour-alert
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py main_production:app
    envVars:
      - key: PORT
        value: 8080
      - key: TELEGRAM_TOKEN
        value: 8505180201:AAGOSkhXHRu77OlRMu0PZCbKtYMEr1tRGAk
      - key: TELEGRAM_CHAT_ID
        value: 838429342
